// ui-themes.ts
export const UI_THEMES = {
  "joe-dark": {
    "--sidebar-bg": "#1e1e1e",
    "--sidebar-fg": "#ccc",
    "--sidebar-button-bg": "#2a2a2a",
    "--sidebar-button-fg": "#eee",
    "--sidebar-button-border": "#444",
    "--sidebar-input-bg": "#333",
    "--sidebar-input-fg": "#fff",
    "--sidebar-input-border": "#555",
    "--toolbar-bg": "#1A1A1A",
    "--toolbar-fg": "#E0E0E0",
    "--panel-bg": "#0D0D0D",
    "--terminal-bg": "#0D0D0D",
    // "--terminal-fg": "#E0E0E0",
    // "--terminal-border": "#333",
    "--terminal-fg": "#00FF00",
    "--terminal-input-bg": "#111",
    "--terminal-input-fg": "#00FF00",
    "--terminal-prompt-fg": "#00FF00",
    "--terminal-button-bg": "#333",
    "--terminal-button-hover-bg": "#444",
    "--terminal-button-fg": "#00FF00",
    "--terminal-button-border": "#00FF00",
    "--terminal-border": "#333",
    "--editor-bg": "#0D001A",
    "--editor-fg": "#FFFFFF",
  },
  "joe-light": {
    "--sidebar-bg": "#F3F3F3",
    "--sidebar-fg": "#333333",
    "--sidebar-button-bg": "#DEDCDC",
    "--sidebar-button-fg": "#000000",
    "--sidebar-button-border": "#444",
    "--sidebar-input-bg": "#333",
    "--sidebar-input-fg": "#fff",
    "--sidebar-input-border": "#555",
    "--toolbar-bg": "#FFFFFF",
    "--toolbar-fg": "#000000",
    "--panel-bg": "#FFFFFF",
    // "--terminal-bg": "#0D0D0D",
    // "--terminal-fg": "#E0E0E0",
    // "--terminal-border": "#333",
    "--terminal-bg": "#FFFFFF",
    "--terminal-fg": "#222222",
    "--terminal-input-bg": "#F0F0F0",
    "--terminal-input-fg": "#222222",
    "--terminal-prompt-fg": "#444444",
    "--terminal-button-bg": "#DDDDDD",
    "--terminal-button-hover-bg": "#CCCCCC",
    "--terminal-button-fg": "#222222",
    "--terminal-button-border": "#888888",
    "--terminal-border": "#CCCCCC",
    "--editor-bg": "#0D001A",
    "--editor-fg": "#FFFFFF",
  },
} as const;
