[package]
name = "my-code-editor"
version = "0.1.0"
description = "My Code Editor IDE"
authors = ["you"]
edition = "2021"

[lib]
name = "my_code_editor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2.4.2"
trash = "3"
# A voir si je garde plugin shell car pas persistant...
tauri-plugin-shell = "2.3.3"
# Terminal persistant PTY: Dernière version disponible !
portable-pty = "=0.9.0"

# ✅ Ajout nécessaire pour ton terminal persistant
# tokio = { version = "1", features = ["full"] }
