import type { MenuSection } from "../types/menuTypes";

/**
 * Top-level menu configuration. Each entry corresponds to a menu
 * button in the TitleBar. Items dispatch a `menu-action` CustomEvent
 * via MenuDropdown, except `__sep__` which renders a separator.
 */
export const TOP_MENUS: MenuSection[] = [
  {
    label: "File",
    items: [
      { label: "New File",        shortcut: "Ctrl+N",        action: "file:new" },
      { label: "New Window",      shortcut: "Ctrl+Shift+N",  action: "file:new-window" },
      { label: "Open File…",      shortcut: "Ctrl+O",        action: "file:open" },
      { label: "Open Folder…",    shortcut: "Ctrl+K Ctrl+O", action: "file:open-folder" },
      { label: "Open Recent",                                action: "file:open-recent" },
      { label: "__sep__",                                    action: "" },
      { label: "Save",            shortcut: "Ctrl+S",        action: "file:save" },
      { label: "Save As…",        shortcut: "Ctrl+Shift+S",  action: "file:save-as" },
      { label: "Save All",        shortcut: "Ctrl+K S",      action: "file:save-all" },
      { label: "__sep__",                                    action: "" },
      { label: "Close Editor",    shortcut: "Ctrl+W",        action: "file:close-editor" },
      { label: "Close Window",    shortcut: "Ctrl+Shift+W",  action: "window:close" },
      { label: "__sep__",                                    action: "" },
      { label: "Exit",            shortcut: "Alt+F4",        action: "app:exit" },
    ],
  },
  {
    label: "Edit",
    items: [
      { label: "Undo",            shortcut: "Ctrl+Z",       action: "edit:undo" },
      { label: "Redo",            shortcut: "Ctrl+Y",       action: "edit:redo" },
      { label: "__sep__",                                   action: "" },
      { label: "Cut",             shortcut: "Ctrl+X",       action: "edit:cut" },
      { label: "Copy",            shortcut: "Ctrl+C",       action: "edit:copy" },
      { label: "Paste",           shortcut: "Ctrl+V",       action: "edit:paste" },
      { label: "__sep__",                                   action: "" },
      { label: "Find",            shortcut: "Ctrl+F",       action: "edit:find" },
      { label: "Replace",         shortcut: "Ctrl+H",       action: "edit:replace" },
      { label: "Find in Files",   shortcut: "Ctrl+Shift+F", action: "edit:find-in-files" },
    ],
  },
  {
    label: "View",
    items: [
      { label: "Command Palette", shortcut: "Ctrl+Shift+P", action: "view:command-palette" },
      { label: "__sep__",                                   action: "" },
      { label: "Explorer",        shortcut: "Ctrl+Shift+E", action: "view:explorer" },
      { label: "Search",          shortcut: "Ctrl+Shift+F", action: "view:search" },
      { label: "Source Control",  shortcut: "Ctrl+Shift+G", action: "view:git" },
      { label: "Run & Debug",     shortcut: "Ctrl+Shift+D", action: "view:run-debug" },
      { label: "Extensions",      shortcut: "Ctrl+Shift+X", action: "view:extensions" },
      { label: "__sep__",                                   action: "" },
      { label: "Toggle Sidebar",  shortcut: "Ctrl+B",       action: "view:toggle-sidebar" },
      { label: "Toggle Right Panel", shortcut: "Ctrl+Alt+B", action: "view:toggle-right" },
      { label: "Toggle Bottom Panel", shortcut: "Ctrl+J",   action: "view:toggle-bottom" },
      { label: "Toggle Full Screen", shortcut: "F11",       action: "view:fullscreen" },
      { label: "Zen Mode",        shortcut: "Ctrl+K Z",     action: "view:zen" },
    ],
  },
  {
    label: "Navigate",
    items: [
      { label: "Go to File…",       shortcut: "Ctrl+P",       action: "nav:file" },
      { label: "Go to Symbol…",     shortcut: "Ctrl+Shift+O", action: "nav:symbol" },
      { label: "Go to Line…",       shortcut: "Ctrl+G",       action: "nav:line" },
      { label: "__sep__",                                     action: "" },
      { label: "Go to Definition",  shortcut: "F12",          action: "nav:definition" },
      { label: "Go to Declaration",                           action: "nav:declaration" },
      { label: "Go to References",  shortcut: "Shift+F12",    action: "nav:references" },
      { label: "__sep__",                                     action: "" },
      { label: "Back",              shortcut: "Alt+Left",     action: "nav:back" },
      { label: "Forward",           shortcut: "Alt+Right",    action: "nav:forward" },
    ],
  },
  {
    label: "Code",
    items: [
      { label: "Format Document",   shortcut: "Shift+Alt+F",  action: "code:format" },
      { label: "Format Selection",  shortcut: "Ctrl+K Ctrl+F", action: "code:format-selection" },
      { label: "__sep__",                                     action: "" },
      { label: "Toggle Line Comment",  shortcut: "Ctrl+/",    action: "code:toggle-line-comment" },
      { label: "Toggle Block Comment", shortcut: "Shift+Alt+A", action: "code:toggle-block-comment" },
      { label: "__sep__",                                     action: "" },
      { label: "Move Line Up",      shortcut: "Alt+Up",       action: "code:move-up" },
      { label: "Move Line Down",    shortcut: "Alt+Down",     action: "code:move-down" },
      { label: "Duplicate Line",    shortcut: "Shift+Alt+Down", action: "code:duplicate" },
      { label: "Delete Line",       shortcut: "Ctrl+Shift+K", action: "code:delete-line" },
    ],
  },
  {
    label: "Refactor",
    items: [
      { label: "Rename Symbol",        shortcut: "F2",        action: "refactor:rename" },
      { label: "Extract Function",                            action: "refactor:extract-function" },
      { label: "Extract Variable",                            action: "refactor:extract-variable" },
      { label: "__sep__",                                     action: "" },
      { label: "Inline",                                      action: "refactor:inline" },
      { label: "Change Signature…",                           action: "refactor:change-signature" },
      { label: "Organize Imports",     shortcut: "Shift+Alt+O", action: "refactor:organize-imports" },
    ],
  },
  {
    label: "Run",
    items: [
      { label: "Run",               shortcut: "Shift+F10",    action: "run:run" },
      { label: "Debug",             shortcut: "Shift+F9",     action: "run:debug" },
      { label: "Stop",              shortcut: "Ctrl+F2",      action: "run:stop" },
      { label: "__sep__",                                     action: "" },
      { label: "Toggle Breakpoint", shortcut: "F9",           action: "run:breakpoint" },
      { label: "Step Over",         shortcut: "F10",          action: "run:step-over" },
      { label: "Step Into",         shortcut: "F11",          action: "run:step-into" },
      { label: "Step Out",          shortcut: "Shift+F11",    action: "run:step-out" },
      { label: "__sep__",                                     action: "" },
      { label: "Edit Configurations…",                        action: "run:configurations" },
    ],
  },
  {
    label: "Tools",
    items: [
      { label: "Terminal",          shortcut: "Ctrl+`",       action: "tools:terminal" },
      { label: "Tasks: Run Task…",                            action: "tools:run-task" },
      { label: "__sep__",                                     action: "" },
      { label: "Package Manager…",                            action: "tools:packages" },
      { label: "External Tools…",                             action: "tools:external" },
      { label: "__sep__",                                     action: "" },
      { label: "Settings",          shortcut: "Ctrl+,",       action: "tools:settings" },
      { label: "Keyboard Shortcuts", shortcut: "Ctrl+K Ctrl+S", action: "tools:shortcuts" },
    ],
  },
  {
    label: "Git",
    items: [
      { label: "Commit…",           shortcut: "Ctrl+K",       action: "git:commit" },
      { label: "Push",                                        action: "git:push" },
      { label: "Pull",                                        action: "git:pull" },
      { label: "Fetch",                                       action: "git:fetch" },
      { label: "__sep__",                                     action: "" },
      { label: "Branches…",                                   action: "git:branches" },
      { label: "Stash Changes",                               action: "git:stash" },
      { label: "Show History",                                action: "git:history" },
      { label: "__sep__",                                     action: "" },
      { label: "Clone Repository…",                           action: "git:clone" },
    ],
  },
  {
    label: "Window",
    items: [
      { label: "Minimize",          action: "window:minimize" },
      { label: "Toggle Maximize",   action: "window:toggle-maximize" },
      { label: "__sep__",           action: "" },
      { label: "Reload Window",     shortcut: "Ctrl+R", action: "window:reload" },
      { label: "Close Window",      shortcut: "Ctrl+Shift+W", action: "window:close" },
    ],
  },
  {
    label: "Help",
    items: [
      { label: "Welcome",                                     action: "help:welcome" },
      { label: "Documentation",                               action: "help:docs" },
      { label: "Keyboard Shortcuts Reference", shortcut: "Ctrl+K Ctrl+R", action: "help:shortcuts" },
      { label: "__sep__",                                     action: "" },
      { label: "Report Issue",                                action: "help:report-issue" },
      { label: "Check for Updates…",                          action: "help:updates" },
      { label: "__sep__",                                     action: "" },
      { label: "About",                                       action: "help:about" },
    ],
  },
];

